// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.1
// source: user_mgmt.proto

package out

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FirstName     string                 `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Age           uint32                 `protobuf:"varint,3,opt,name=age,proto3" json:"age,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	PhNo          string                 `protobuf:"bytes,5,opt,name=phNo,proto3" json:"phNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewUser) Reset() {
	*x = NewUser{}
	mi := &file_user_mgmt_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewUser) ProtoMessage() {}

func (x *NewUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgmt_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewUser.ProtoReflect.Descriptor instead.
func (*NewUser) Descriptor() ([]byte, []int) {
	return file_user_mgmt_proto_rawDescGZIP(), []int{0}
}

func (x *NewUser) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *NewUser) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *NewUser) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *NewUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *NewUser) GetPhNo() string {
	if x != nil {
		return x.PhNo
	}
	return ""
}

type UserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	User          *NewUser               `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserResponse) Reset() {
	*x = UserResponse{}
	mi := &file_user_mgmt_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserResponse) ProtoMessage() {}

func (x *UserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgmt_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserResponse.ProtoReflect.Descriptor instead.
func (*UserResponse) Descriptor() ([]byte, []int) {
	return file_user_mgmt_proto_rawDescGZIP(), []int{1}
}

func (x *UserResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserResponse) GetUser() *NewUser {
	if x != nil {
		return x.User
	}
	return nil
}

type UserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserId) Reset() {
	*x = UserId{}
	mi := &file_user_mgmt_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserId) ProtoMessage() {}

func (x *UserId) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgmt_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserId.ProtoReflect.Descriptor instead.
func (*UserId) Descriptor() ([]byte, []int) {
	return file_user_mgmt_proto_rawDescGZIP(), []int{2}
}

func (x *UserId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ModifiedUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Age           uint32                 `protobuf:"varint,4,opt,name=age,proto3" json:"age,omitempty"`
	Email         string                 `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	PhNo          string                 `protobuf:"bytes,6,opt,name=phNo,proto3" json:"phNo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ModifiedUser) Reset() {
	*x = ModifiedUser{}
	mi := &file_user_mgmt_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ModifiedUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ModifiedUser) ProtoMessage() {}

func (x *ModifiedUser) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgmt_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ModifiedUser.ProtoReflect.Descriptor instead.
func (*ModifiedUser) Descriptor() ([]byte, []int) {
	return file_user_mgmt_proto_rawDescGZIP(), []int{3}
}

func (x *ModifiedUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ModifiedUser) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *ModifiedUser) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *ModifiedUser) GetAge() uint32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *ModifiedUser) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *ModifiedUser) GetPhNo() string {
	if x != nil {
		return x.PhNo
	}
	return ""
}

type ResponseMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Resp          string                 `protobuf:"bytes,1,opt,name=resp,proto3" json:"resp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseMessage) Reset() {
	*x = ResponseMessage{}
	mi := &file_user_mgmt_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseMessage) ProtoMessage() {}

func (x *ResponseMessage) ProtoReflect() protoreflect.Message {
	mi := &file_user_mgmt_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseMessage.ProtoReflect.Descriptor instead.
func (*ResponseMessage) Descriptor() ([]byte, []int) {
	return file_user_mgmt_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseMessage) GetResp() string {
	if x != nil {
		return x.Resp
	}
	return ""
}

var File_user_mgmt_proto protoreflect.FileDescriptor

const file_user_mgmt_proto_rawDesc = "" +
	"\n" +
	"\x0fuser_mgmt.proto\x12\busermgmt\"\x7f\n" +
	"\aNewUser\x12\x1c\n" +
	"\tfirstName\x18\x01 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x02 \x01(\tR\blastName\x12\x10\n" +
	"\x03age\x18\x03 \x01(\rR\x03age\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x12\n" +
	"\x04phNo\x18\x05 \x01(\tR\x04phNo\"E\n" +
	"\fUserResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x04user\x18\x02 \x01(\v2\x11.usermgmt.NewUserR\x04user\"\x18\n" +
	"\x06UserId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x94\x01\n" +
	"\fModifiedUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tfirstName\x18\x02 \x01(\tR\tfirstName\x12\x1a\n" +
	"\blastName\x18\x03 \x01(\tR\blastName\x12\x10\n" +
	"\x03age\x18\x04 \x01(\rR\x03age\x12\x14\n" +
	"\x05email\x18\x05 \x01(\tR\x05email\x12\x12\n" +
	"\x04phNo\x18\x06 \x01(\tR\x04phNo\"%\n" +
	"\x0fResponseMessage\x12\x12\n" +
	"\x04resp\x18\x01 \x01(\tR\x04resp2\xfc\x01\n" +
	"\x0eUserManagement\x126\n" +
	"\aAddUser\x12\x11.usermgmt.NewUser\x1a\x16.usermgmt.UserResponse\"\x00\x125\n" +
	"\aGetUser\x12\x10.usermgmt.UserId\x1a\x16.usermgmt.UserResponse\"\x00\x12>\n" +
	"\n" +
	"UpdateUser\x12\x16.usermgmt.ModifiedUser\x1a\x16.usermgmt.UserResponse\"\x00\x12;\n" +
	"\n" +
	"DeleteUser\x12\x10.usermgmt.UserId\x1a\x19.usermgmt.ResponseMessage\"\x00B\x06Z\x04out/b\x06proto3"

var (
	file_user_mgmt_proto_rawDescOnce sync.Once
	file_user_mgmt_proto_rawDescData []byte
)

func file_user_mgmt_proto_rawDescGZIP() []byte {
	file_user_mgmt_proto_rawDescOnce.Do(func() {
		file_user_mgmt_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_mgmt_proto_rawDesc), len(file_user_mgmt_proto_rawDesc)))
	})
	return file_user_mgmt_proto_rawDescData
}

var file_user_mgmt_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_mgmt_proto_goTypes = []any{
	(*NewUser)(nil),         // 0: usermgmt.NewUser
	(*UserResponse)(nil),    // 1: usermgmt.UserResponse
	(*UserId)(nil),          // 2: usermgmt.UserId
	(*ModifiedUser)(nil),    // 3: usermgmt.ModifiedUser
	(*ResponseMessage)(nil), // 4: usermgmt.ResponseMessage
}
var file_user_mgmt_proto_depIdxs = []int32{
	0, // 0: usermgmt.UserResponse.user:type_name -> usermgmt.NewUser
	0, // 1: usermgmt.UserManagement.AddUser:input_type -> usermgmt.NewUser
	2, // 2: usermgmt.UserManagement.GetUser:input_type -> usermgmt.UserId
	3, // 3: usermgmt.UserManagement.UpdateUser:input_type -> usermgmt.ModifiedUser
	2, // 4: usermgmt.UserManagement.DeleteUser:input_type -> usermgmt.UserId
	1, // 5: usermgmt.UserManagement.AddUser:output_type -> usermgmt.UserResponse
	1, // 6: usermgmt.UserManagement.GetUser:output_type -> usermgmt.UserResponse
	1, // 7: usermgmt.UserManagement.UpdateUser:output_type -> usermgmt.UserResponse
	4, // 8: usermgmt.UserManagement.DeleteUser:output_type -> usermgmt.ResponseMessage
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_mgmt_proto_init() }
func file_user_mgmt_proto_init() {
	if File_user_mgmt_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_mgmt_proto_rawDesc), len(file_user_mgmt_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_user_mgmt_proto_goTypes,
		DependencyIndexes: file_user_mgmt_proto_depIdxs,
		MessageInfos:      file_user_mgmt_proto_msgTypes,
	}.Build()
	File_user_mgmt_proto = out.File
	file_user_mgmt_proto_goTypes = nil
	file_user_mgmt_proto_depIdxs = nil
}
